services:
  - type: web
    name: colegio-finanzas-app
    env: node
    plan: free
    branch: main
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: cd server && npm run start
    rootDir: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "4000"
      - key: VITE_API_URL
        value: "/api"
        sync: false
